version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: liquibase-postgres
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: liquibase
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquibase -d myapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: