services:
  db:
    image: postgres:15-alpine
    container_name: warehouse-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: liquibase
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U liquibase -d warehouse"]
      interval: 5s
      timeout: 3s
      retries: 20


  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
      SPRING_DATASOURCE_USERNAME: liquibase
      SPRING_DATASOURCE_PASSWORD: securepassword
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGELOG: classpath:./db.changelog-master.yaml
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: