version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: warehouse_db
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: liquibase
      POSTGRES_PASSWORD: liquibase
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquibase -d warehouse"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
      SPRING_DATASOURCE_USERNAME: liquibase
      SPRING_DATASOURCE_PASSWORD: liquibase
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGELOG: classpath:/db/changelog/db.changelog-master.yaml
      SPRINGDOC_API_DOCS_PATH: /api/v3/api-docs
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
