server:
  port: 8761

spring:
  application:
    name: eureka-config-server
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: classpath:/docker-configs


eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
  server:
    # Disable self-preservation for development (not recommended for production)
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000


management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator

  endpoint:
    health:
      show-details=always:
